### ISSUE TITLE
Add "receipt" icon

### ISSUE THREAD

**Issue by Alexson-Felipe** [primefaces/primeicons#1003]

**Comment by jepsar** [comment]
Do you have an example?

**Comment by Alexson-Felipe** [comment]
Of course 

![ico1](https://github.com/primefaces/primeicons/assets/10691297/f83c8c74-308f-4a18-a8f0-dc74e63d41b9)

![forma-de-pagamento](https://github.com/primefaces/primeicons/assets/10691297/e741aaba-7698-4a99-8c9e-8328509dbf95)

**Comment by LauraCorreaO** [comment]
did you get it?
