### ISSUE TITLE
Add 'Aircraft Engine' icon

### ISSUE THREAD

**Issue by Ciaran97** [primefaces/primeicons#1010]
like this flaticon [https://www.flaticon.com/free-icon/turbine_9647643?term=aircraft+engine&page=1&position=9&origin=tag&related_id=9647643](https://www.flaticon.com/free-icon/turbine_9647643?term=aircraft+engine&page=1&position=9&origin=tag&related_id=9647643)

**Comment by jepsar** [comment]
Why? This seems very specific.

**Comment by Ciaran97** [comment]
> Why? This seems very specific.

I suppose so, could also be used as a turbine for other use cases. Could be done to look more like a turbine than an engine but there is no similar icon that slightly resembles what i need...

**Comment by onursenture** [comment]
Hi, Sorry but there is no common use-case of this icon for other users of PrimeIcons. Thanks for suggestion.
