### ISSUE TITLE
Is this library alive?

### ISSUE THREAD

**Issue by inad9300** [primefaces/primeicons#1034]
In multiple occasions I have tried to ask about the state of this library, unsuccessfully. This is one more attempt to see if I have more luck than in the past. I'm not asking for any action to be taken, just for information to be provided.

As it stands today, the icon library is very limited, as made evident by the hundreds of user requests. Yet, since it already comes with PrimeReact et al., ideally one would like to use it, before introducing an extra dependency. So, I would like to know: are you planning on ever extending it again, or is it hopeless for us to keep expecting this?

**Comment by jepsar** [comment]
This is an issue tracker. Not a forum. Please use [discussions](https://github.com/orgs/primefaces/discussions/categories/primeicons).

**Comment by onursenture** [comment]
> This is an issue tracker. Not a forum. Please use [discussions](https://github.com/orgs/primefaces/discussions/categories/primeicons).

+1
