### ISSUE TITLE
suggestion: emotion icon

### ISSUE THREAD

**Issue by SilvanoGMatta** [primefaces/primeicons#1048]
### Discussed in https://github.com/orgs/primefaces/discussions/117

<div type='discussions-op-text'>

<sup>Originally posted by **SilvanoGMatta** September 26, 2023</sup>
Sugest Icon Emotion
![image](https://github.com/primefaces/community/assets/25065978/bf0e070f-e426-4ad1-97cf-ef7dc6d8d8a1)
</div>
similar : fa-regular fa-face-smile

**Comment by jepsar** [comment]
Duplicate of #383
