### ISSUE TITLE
HeadPhone

### ISSUE THREAD

**Issue by Ahmed-Madher-Alsaeg** [primefaces/primeicons#1060]
Please add a headphone icon 

It is very important

**Comment by jepsar** [comment]
Duplicate of #91

Adding claims as "It is very important" will not increase its priority. You will be better of searching for existing issues and upvoting them instead of creating duplicates.

**Comment by onursenture** [comment]
> Duplicate of #91
> 
> Adding claims as "It is very important" will not increase its priority. You will be better of searching for existing issues and upvoting them instead of creating duplicates.

+1
