### ISSUE TITLE
New Icons Needed

### ISSUE THREAD

**Issue by brandon-philpot** [primefaces/primeicons#1069]
1. replace Twitter icon with X.com logo
2. different forms of payment (Square, Stripe, Cash App, etc)
3. id card or drivers license, passport
4. map location
5. video game manufacture icons (nintendo, xbox, playstation, etc)
6. computer related icons (ram or memory, cpu, ssd or hdd, etc)

**Comment by jepsar** [comment]
@brandon-philpot Please check for duplicates first and create one issue per icon.
