### ISSUE TITLE
Add new Twitter icon

### ISSUE THREAD

**Issue by Nat-SB** [primefaces/primeicons#1078]
As the Twitter icon has changed would be nice to have the new Twitter icon.
This is some examples:
![Screenshot 2024-01-03 at 15 23 25](https://github.com/primefaces/primeicons/assets/125361038/0feba03d-43c6-4c1a-a7c7-7c9d42c9caaa)
![Screenshot 2024-01-03 at 15 25 04](https://github.com/primefaces/primeicons/assets/125361038/5d7d03f0-34a6-4d3b-b6e3-c0fc422e3a5d)

**Comment by onursenture** [comment]
> @Nat-SB duplicate of #1006 and #1033

+1
