### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by NAMSGithub** [primefaces/primeicons#108]
Sorry if this is a noob question, but I can't figure out how to map an icon to the class needed to use it.

Looking at the CSS used by my site I had a guess for how to create the little "x" icon but surely there is a list?

`<i class="pi pi-times"></i>`

**Comment by onursenture** [comment]
Official website will be released soon. In the meanwhile, you can refer http://primefaces.org/primeng/#/icons here for the list.

**Comment by pljspahn** [comment]
You may want to add a link to that page somewhere. I was unable to find it until I found it here.
