### ISSUE TITLE
Where are new icons?

### ISSUE THREAD

**Issue by vokic** [primefaces/primeicons#1087]
Hi, I don't want to sound rude, but has any of the icons been added per requests? Am I looking at a different set? Is there any that is more up to date than this?

https://primeng.org/icons

Also, I want to contribute in creating icons if that is an issue.

✌

**Comment by jepsar** [comment]
This is an issue tracker, not a forum. For questions, please use https://github.com/orgs/primefaces/discussions

**Comment by vokic** [comment]
> This is an issue tracker, not a forum. For questions, please use https://github.com/orgs/primefaces/discussions

Ok, it can be deleted
