### ISSUE TITLE
Request to add more globe icon like 

### ISSUE THREAD

**Issue by suman-novelty** [primefaces/primeicons#1098]
https://media.istockphoto.com/id/1137975660/vector/1901-m40-i030-n020-s-c12-144256648-earth-globe-icons-world-map-geography-internet-global.webp?s=2048x2048&w=is&k=20&c=oZGKkAbHlSlqKdB3fFAyvzXlqSLZr_HvYfVoa51StBI=

**Comment by jepsar** [comment]
Duplicate of #900

**Comment by onursenture** [comment]
> Duplicate of #900

+1
