### ISSUE TITLE
Add Moon Fill icon

### ISSUE THREAD

**Issue by alexdeweert** [primefaces/primeicons#1103]
You have an icon for `pi-moon`, would love to see `pi-moon-fill` as well. Thank you.

**Comment by jepsar** [comment]
See #471

**Comment by onursenture** [comment]
We only add -fill alternatives if the icon has a potential toggle behavior like heart / thumb-up, etc. We'll continue to consider an icon to represent 'dim' mode on #471, as @jepsar suggested.
