### ISSUE TITLE
Add graduation hat icon

### ISSUE THREAD

**Issue by sanjils** [primefaces/primeicons#1107]

**Comment by jepsar** [comment]
Please request one icon per issue and search for duplicates first.

**Comment by sanjils** [comment]
> Please request one icon per issue and search for duplicates first.
> 
> Duplicate of #703

is it already added ? I can't see

**Comment by onursenture** [comment]
> Please request one icon per issue and search for duplicates first.
> 
> Duplicate of #703

+1

> > Please request one icon per issue and search for duplicates first.
> > Duplicate of #703
> 
> is it already added ? I can't see

Not yet, but the issue is duplicate.
