### ISSUE TITLE
Add system status icon

### ISSUE THREAD

**Issue by ddsc04** [primefaces/primeicons#1118]
Example of icon in pic below.

![image](https://github.com/primefaces/primeicons/assets/162183753/8c0c1381-ca6f-493a-91f3-dd6d93ddb469)

**Comment by ddsc04** [comment]
Alternative system status icon.

![image](https://github.com/primefaces/primeicons/assets/162183753/7c696459-0e8e-4fc8-8644-161e2ea12c94)

**Comment by onursenture** [comment]
Hi, Since there is no common use-case for this icon, we decided not to add. Thank you for suggestion.
