### ISSUE TITLE
Prime Vue, AI icon ist working. 

### ISSUE THREAD

**Issue by adydeeram** [primefaces/primeicons#1145]
Here is the description and details for the issue. 
Prime-vue version: 3.51.0
Prime icons version : 7.0.0

Other details

`<i class="pi pi-microchip-ai"></i>`

![image](https://github.com/primefaces/primeicons/assets/61200310/d3f84bbe-3282-41e0-9afa-dc9d46e49137)

**Comment by onursenture** [comment]
Hi, We couldn't replicate the issue. It's probably not related to PrimeIcons. You may consider to open issue to PrimeVue repo.

<img width="1276" alt="image" src="https://github.com/primefaces/primeicons/assets/244957/30fc61b2-6c28-465a-b582-a8e56bebc6cb">
