### ISSUE TITLE
Add "bug" icon

### ISSUE THREAD

**Issue by maxi-smidt** [primefaces/primeicons#1209]

**Comment by maxi-smidt** [comment]
![bug_report_24dp_5F6368_FILL0_wght400_GRAD0_opsz24](https://github.com/user-attachments/assets/6356ae60-3a10-4ed6-b43f-44f554181d1e)

**Comment by maxi-smidt** [comment]
source [Google Fonts](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:bug_report:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=bug&icon.size=24&icon.color=%235f6368&icon.platform=web)

**Comment by jepsar** [comment]
Duplicate of #217
