### ISSUE TITLE
Delete file icon for p-fileupload is missing

### ISSUE THREAD

**Issue by stigperez** [primefaces/primeicons#121]
**Current behavior**
When adding a p-fileupload element and adding a file, the "delete file" icon is not shown. It looks like the element renders 2 span-containers with one of them having a class pointing to "ui-button-icon-left ui-clickable pi pi-times". Replacing "pi pi-times" with the font-awesome equivalent of "fa fa-times" shows the font-awesome icon.

**Expected behavior**
Adding the p-fileupload element and adding a file correctly shows the "delete file" icon.

**Minimal reproduction of the problem with instructions**
1. Run `npm install primeng primeicons`
2. Import the `FileUploadModule` from `primeng/fileupload` in your module file.
3. Add the p-fileupload element to the component markup
4. Open a browser, navigate to the component and add a file to the upload element

**What is the motivation / use case for changing the behavior?**
Either to add the pi-times icon or be able to create a fallback to fa-times

**Please tell us about your environment:**
Windows 10 Pro
Visual Studio Code 1.27.1
Node 8.11.4
npm 6.4.1
Angular 6.1.6
TypeScript 2.7.2
primeng 6.1.3
primeicons 1.0.0-beta.10
@angular-cli 6.1.5
Google Chrome 68.0.3440.106 64-bit

Not the most game-breaking issue I admit but now you know :-)

**Comment by yigitfindikli** [comment]
Hi,
I couldn't duplicate with PrimeNG 8 and 7.1.3. Do you still have this problem?
Best Regards.

**Comment by stigperez** [comment]
Hi yigitfindikli I just tried replicating the issue with PrimeNG 8.0.1 but was unable to do so. The icon is now displayed properly so maybe it was an issue with the CSS file reference on my side. Thanks for looking into it :-)

**Comment by yigitfindikli** [comment]
@stigperez Glad to hear, always happy to help!
