### ISSUE TITLE
pi-asterisk doesn't work

### ISSUE THREAD

**Issue by Puplum** [primefaces/primeicons#1214]
![image](https://github.com/user-attachments/assets/d93d22f5-ab11-4573-919f-b37cb161bd8b)
When I try to call pi-asterisk, the icon doesn't display, but if I change it to pi-check, for example, it works

**Comment by jepsar** [comment]
It's working here https://www.primefaces.org/showcase/icons.xhtml

Are you using the correct version?

**Comment by Puplum** [comment]
> It's working here https://www.primefaces.org/showcase/icons.xhtml
> 
> Are you using the correct version?

![image](https://github.com/user-attachments/assets/d156f19e-1a5d-4e27-80ac-7dfc202d1ded)

**Comment by jepsar** [comment]
Are you sure that that version is actually loaded?

**Comment by Puplum** [comment]
![image](https://github.com/user-attachments/assets/c2376334-cff9-4782-80e2-013fd0281600)
I have this

**Comment by Puplum** [comment]
mb it' not supported by firefox
