### ISSUE TITLE
Add "microsoft" icon

### ISSUE THREAD

**Issue by cyberrranger** [primefaces/primeicons#122]
thx

**Comment by onursenture** [comment]
Can we add these brand logos without permission to such a project with MIT license? Is there any information about this?

**Comment by cyberrranger** [comment]
i found in FA this icon https://fontawesome.com/icons/microsoft?style=brands

and on https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx is only with the text "Microsoft"

**Comment by onursenture** [comment]
Cool it'll be added in 2-3 days.
