### ISSUE TITLE
Possibility of getting the SVG source files of icons to create Adobe XD stickersheet 

### ISSUE THREAD

**Issue by davisb10** [primefaces/primeicons#138]
I'm trying to create an (unofficial) Adobe XD stickersheet to use in my designs. I originally tried to extract them by uploading the main primeicons.svg file to IcoMoon and extracting but they are coming out really pixelated.

Is there a possibility of getting the individual SVG source files for each icon?

Thanks so much!

**Comment by onursenture** [comment]
d6f1ae247cd99d8281f0e26d1330b34079628cc7 ⚡️

**Comment by davisb10** [comment]
Thanks! You all are awesome! I'll 'watch' this repository and try to keep my stickersheet up to date with the provided icons in my own repo. https://github.com/davisb10/primeicons-adobexd-stickersheet
