### ISSUE TITLE
primefaces drag component

### ISSUE THREAD

**Issue by talentvinayak** [primefaces/primeicons#139]
i can't get panel drag positions(eg. left and top values) in existing drag primefaces component.

**Comment by onursenture** [comment]
Please use forum.primefaces.org for PrimeFaces related questions. Thank you.

**Comment by talentvinayak** [comment]
> Please use [forum.primefaces.org](https://forum.primefaces.org) for PrimeFaces related questions. Thank you.

Okay 
Thank you very much
