### ISSUE TITLE
Add "file-o" icon

### ISSUE THREAD

**Issue by ChrisHunter-Johnson** [primefaces/primeicons#140]
Could there be a new document icon like fa-file-o?

**Comment by chrishj59** [comment]
Reference: https://fontawesome.com/v4.7.0/icon/file-o

**Comment by VsevolodGolovanov** [comment]
What's the difference between file and file-o? They look the same.

**Comment by onursenture** [comment]
> What's the difference between file and file-o? They look the same.

No difference. It's for backward compatibility. Icons were all filled and there were some line icons back in PrimeIcons 1.
