### ISSUE TITLE
difficulty finding icons

### ISSUE THREAD

**Issue by leonetosoft** [primefaces/primeicons#148]
It does not have a proper list of icones as documentation, just fontawesome, that we can find icones and know which "class" to use ..
In the beginning it has all the icons but in image format, it is not possible to search the class easily ...

**Comment by sgikas** [comment]
Helllo @leonetosoft,

i have found this one:
https://www.primefaces.org/primeng/#/icons

Regards,
Stelios

**Comment by onursenture** [comment]
Hi @leonetosoft, We're currently not planning to make a separate website for PrimeIcons. You can browse and search all icons on; 

https://www.primefaces.org/primeng/#/icons
http://primefaces.org/primereact/#/icons
http://primefaces.org/showcase/ui/misc/primeicons.xhtml

**Comment by onursenture** [comment]
I added the links to the readme.

**Comment by leonetosoft** [comment]
@onursenture tanks
