### ISSUE TITLE
Add inverse "pi-sort" icon (as "pi-sort-inverse")

### ISSUE THREAD

**Issue by mlc-mlapis** [primefaces/primeicons#149]
To indicate that a content - column based (and clickable for a user), is sortable in both directions in a moment when the content is sorted by another column.

The icon might look like:

![image](https://user-images.githubusercontent.com/5693835/50934412-da1d0500-1468-11e9-9cb7-dbdad20c3c96.png)

**Comment by onursenture** [comment]
Hi, Is there any example on FontAwesome for this icon? I cannot find it, and the example you gave is not appropriate for the case you explained imho.

**Comment by mlc-mlapis** [comment]
@onursenture ... there is **sort** icon on https://fontawesome.com/icons?s=regular for the same meaning but I think that my suggestion is better because it's cleaner.

![image](https://user-images.githubusercontent.com/5693835/51752592-277bb200-20b8-11e9-82ae-9ddef3a97543.png)

What I originally thought is that the case when you need to indicate (in the column head) that it's sortable in both directions on a click.
