### ISSUE TITLE
Add inverse "pi-sort" icon (as "pi-sort-inverse")

### ISSUE THREAD

**Issue by mlc-mlapis** [primefaces/primeicons#151]
@onursenture ... I apologize ... closing the previous one was my mistake ... and later I couldn't reopened it.
>
To indicate that a content - column based (and clickable for a user), is sortable in both directions in a moment when the content is sorted by another column.

The icon might look like:

![image](https://user-images.githubusercontent.com/5693835/51753092-4169c480-20b9-11e9-8c2b-0fcd310735e3.png)

EDIT:

 https://github.com/primefaces/primeicons/issues/149

@onursenture ... there is sort icon on https://fontawesome.com/icons?s=regular for the same meaning but I think that my suggestion is better because it's cleaner.

image
![image](https://user-images.githubusercontent.com/5693835/51753106-49296900-20b9-11e9-9373-3bc3e962cfee.png)

What I originally thought is that the case when you need to indicate (in the column head) that it's sortable in both directions on a click.

**Comment by onursenture** [comment]
We decided not to add this one to keep library consistent for now. Thanks.
