### ISSUE TITLE
Add "directions" icon 

### ISSUE THREAD

**Issue by IVmostafa** [primefaces/primeicons#176]
something look like the direction material icon 
https://material.io/tools/icons/?search=directions&style=baseline

**Comment by dawidp-ionoview** [comment]
@onursenture what are the expected date of this getting done? just roughly - days / weeks / months?

**Comment by onursenture** [comment]
@IVmostafa 1 day / 0 week / 0 month. We'll release PrimeIcons 2.0 tomorrow.
