### ISSUE TITLE
Add sort type icons

### ISSUE THREAD

**Issue by AviwT** [primefaces/primeicons#177]
Hi guys!
Would be great to have sort type icons, like sort by alphabet, by number , by amount:
![image](https://user-images.githubusercontent.com/5618778/60871737-fe9d4280-a23b-11e9-9a38-21fc6a0dfc36.png)
Now there is a possibility to specify sort direction, but with these icons it will be possible to point out sort options more specific.

Thanx in advance!

**Comment by onursenture** [comment]
Thank you. This is most probably the best issue of the project ever. The icons needed to be designed are:

- sort-amount-up
- sort-amount-down
- sort-amount-up-alt
- sort-amount-down-alt
- sort-numeric-up
- sort-numeric-down
- sort-numeric-up-alt
- sort-numeric-down-alt
- sort-alpha-up
- sort-alpha-down
- sort-alpha-up-alt
- sort-alpha-down-alt

We'll include all these icons for the 2.0 release.

**Comment by AviwT** [comment]
Great news!!
Thanx!
