### ISSUE TITLE
Add "clipboard" icon

### ISSUE THREAD

**Issue by vimalraj-ponnusamy** [primefaces/primeicons#178]
A cut , copy, paste icon will be useful for clipboard operations in grid

**Comment by onursenture** [comment]
Any example for this?

**Comment by chborntraeger** [comment]
any news on this topic?
maybe like https://fontawesome.com/v4.7.0/icon/clipboard and  https://fontawesome.com/v4.7.0/icon/scissors

**Comment by minzdrav** [comment]
++

**Comment by hecnabae** [comment]
++
