### ISSUE TITLE
Add new icon - Building

### ISSUE THREAD

**Issue by bendhanoa** [primefaces/primeicons#223]
Please add a building icon.

Something like following would be great.

        <svg xmlns=" http://www.w3.org/2000/svg" width="18" height="16" viewBox="0 0 18 16">
                <path fill="#FFF" fill-rule="evenodd" d="M0 0H17.455V16H0z" />
         </svg>

Thank you.

**Comment by onursenture** [comment]
Duplicate of https://github.com/primefaces/primeicons/issues/236
