### ISSUE TITLE
pi-minus and pi-minus-circle do not correspont 

### ISSUE THREAD

**Issue by sdrh** [primefaces/primeicons#23]
With pi-minus and pi-minus-circle you get pi-plus and pi-plus-circle.
Reviewing the code in https://www.primefaces.org/primeng/#/icons 
when presenting pi-minus, pi-plus is presented 
<i _ngcontent-c1="" class="pi pi-plus"></i>
<div _ngcontent-c1="">pi-minus</div>
the same happens for pi-minus-circle

**Comment by onursenture** [comment]
It's fixed for next releases. Thank you.

02d03600ce1d843ceb16fb79ba0563a206c71848
357ba42ddd4df7d1c7533ad2cfe71e397bf4cfcf
