### ISSUE TITLE
Times looks misplaced vertically in a button

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primeicons#237]
Using PrimeIcons with PrimeReact.

The icons don't show up in codesandbox for some reason, but you can just edit the class name in [the PrimeReact button showcase](https://www.primefaces.org/primereact/showcase/#/button) to "pi-times":
![image](https://user-images.githubusercontent.com/8070317/82336540-680ce680-99f3-11ea-8714-410dbf0844d4.png)
Seems like it's 1 pixel higher than the check icon.

I also tried building my app with the latest published to npm PrimeIcons 3.0.0-rc.1 - the problem is still there:
![image](https://user-images.githubusercontent.com/8070317/82337067-039e5700-99f4-11ea-95ad-4906c684ecb8.png)
You can see it's closer to the top than the bottom.

**Comment by VsevolodGolovanov** [comment]
"Trash" too:
![image](https://user-images.githubusercontent.com/8070317/82347289-1a4aab00-9a00-11ea-9d64-a3ee3f147b39.png)

**Comment by onursenture** [comment]
We are updating all icons to fix all alignment issues and modernizing the icon pack. Times icon is also fixed for future releases. Thank you.
