### ISSUE TITLE
CHANGELOG is missing

### ISSUE THREAD

**Issue by dmytro-gokun** [primefaces/primeicons#238]
Is there a changelog for this project somewhere? For example, v3.0.0 was recently released, but it's hard to tell what exactly was changed there compared to v2.

Also, what are the rules for compatibility with different versions of primeng (and rest). I.e., is it safe to use primeicons 3.0.0 with primeng v8? primeng v9? etc.

**Comment by NateRadebaugh** [comment]
Changelog is here:
https://github.com/primefaces/primeicons/blob/master/CHANGELOG.md
