### ISSUE TITLE
RC is listed as "latest" in npm registry

### ISSUE THREAD

**Issue by dmytro-gokun** [primefaces/primeicons#239]
https://www.npmjs.com/package/primeicons

4.0.0-rc.1 is listed is "latest". This violates common npm practices. Instead 3.0.0 should be listed as "latest" and 4.0.0-rc.1 as "next. For example, see how Angular folks do it: https://www.npmjs.com/package/@angular/core

**Comment by onursenture** [comment]
I believe this is not a open issue for now. Please ping us if you think opposite. 
![Uploading image.png…]()
