### ISSUE TITLE
Prefer old calendar icons

### ISSUE THREAD

**Issue by taiducnguyen** [primefaces/primeicons#250]
![image](https://user-images.githubusercontent.com/22149480/86454756-ef1ae180-bd49-11ea-9573-a01a0f1efd8d.png)

Hi guys,

I saw the calendar icons have been changed in version 4.0.
It's quite difficult to understand it means calendar icon, I asked some people about that but they almost prefer version 2.0
![image](https://user-images.githubusercontent.com/22149480/86454291-394f9300-bd49-11ea-8494-0c8a0fb06cfe.png)

Could you please consider about this!

Thanks

**Comment by onursenture** [comment]
Thanks for the suggestion. We're not planning to change calendar icon's style for now.
