### ISSUE TITLE
An icon similar to mail or message

### ISSUE THREAD

**Issue by RajatPanda** [primefaces/primeicons#271]

**Comment by ComputerDaddyGuy** [comment]
Hi,
Does the existing "pi-envelope" fit your needs ?
![image](https://user-images.githubusercontent.com/32534816/91694787-7380b980-eb6d-11ea-96e3-4c8d446c7cad.png)
Regards

**Comment by onursenture** [comment]
We already have the pi-envelope icon. Thank you!
