### ISSUE TITLE
add Social icons: LinkedIn, Facebook, Twitter, Github, Youtube

### ISSUE THREAD

**Issue by neelavar** [primefaces/primeicons#274]
Social icons are very useful which sharing the social handles on the web page elegantly

**Comment by voquanghoa** [comment]
Icon for facebook has available already :D

![image](https://user-images.githubusercontent.com/10450325/93022804-47594400-f615-11ea-8c4b-fa1c881af3af.png)

**Comment by neelavar** [comment]
Yes, other additional social icons like: LinkedIn, Youtube etc. would be very handy

**Comment by mattbodman** [comment]
Vimeo, while you're there please

**Comment by VILLAN3LL3** [comment]
+ twitter 
+ xing

**Comment by onursenture** [comment]
We already have some of them. Can you open issues for Linkedin and Youtube separately if you still need them. Each icon should have its own issue for evaluation. Thank you.
