### ISSUE TITLE
Add travel icons

### ISSUE THREAD

**Issue by VILLAN3LL3** [primefaces/primeicons#282]
e.g. train, plane, taxi, suitcase.
font-awesome examples:
https://fontawesome.com/v4.7.0/icon/plane
https://fontawesome.com/v4.7.0/icon/train
https://fontawesome.com/v4.7.0/icon/taxi
https://fontawesome.com/v4.7.0/icon/suitcase

**Comment by onursenture** [comment]
There is already https://github.com/primefaces/primeicons/issues/219 request for the moment. Can you add other ones as seperate issues please?

**Comment by onursenture** [comment]
Ah pi-briefcase is already implemented too.
