### ISSUE TITLE
Add organigram icon

### ISSUE THREAD

**Issue by MinitySkariaJubin** [primefaces/primeicons#298]

**Comment by onursenture** [comment]
Hi, Can you please share a reference icon?

**Comment by MinitySkariaJubin** [comment]
![1 (1)](https://user-images.githubusercontent.com/12891586/108020193-db568e00-7041-11eb-9d54-4f9fdacce854.png)

**Comment by onursenture** [comment]
pi-sitemap is already added. :) Thank you!
