### ISSUE TITLE
What about woff2 format?

### ISSUE THREAD

**Issue by dheimoz** [primefaces/primeicons#301]
Great work guys. I must say that icons work great with PrimeVue, I am in love with them and if ver 4.1 is released soon with the new icons, Wow, mind blowing.

However, I would like to suggest that format Woff2 should be considered.

It offers greater compression, around 30 or 50% according to release notes:
"The new WOFF 2.0 Web Font compression format offers a 30% average gain over WOFF 1.0 (up to 50%+ in some cases)."
https://blog.chromium.org/2014/05/chrome-36-beta-elementanimate-html.html

Thanks guys.

**Comment by onursenture** [comment]
New woff2 font file is added. You can use it on your css by changing import line. We'll consider to change the CSS after tests.

**Comment by onursenture** [comment]
woff2 added to css. Related commit: 2a8565a3eaae9096435b385085dee4d02bd2b9d6
