### ISSUE TITLE
"Link" and "unlink" icons

### ISSUE THREAD

**Issue by beretheub** [primefaces/primeicons#305]
![image](https://user-images.githubusercontent.com/28962542/99358566-703dd400-28f9-11eb-99d5-c919821e2298.png)
![image](https://user-images.githubusercontent.com/28962542/99358600-7b90ff80-28f9-11eb-805d-86d32323b32a.png)

Hi, 
Would it be possible to add those icons? (link and broken link) 
There are pretty common, would be very helpful!
Thanks!

**Comment by onursenture** [comment]
We have already pi-link, and unfortunately we don't plan unlink for now. Thank you!
