### ISSUE TITLE
Academic/education-related icons

### ISSUE THREAD

**Issue by timothychurchill** [primefaces/primeicons#332]
Could I please request some academic and education-related icons, such as: student, students, teacher, lecturer, professor, principal, classroom, school, college, university, faculty, department, books, library, subject, course, office, etc...

Icons for the two biggest learning systems would also be very helpful: Canvas (https://canvas.instructure.com) and Moodle (https://moodle.org).

Thank you!

**Comment by onursenture** [comment]
Hi, thanks for suggestion but we need separate issues for each icon requests to track. Could you please open separately?
