### ISSUE TITLE
Add "thumbtack" icon

### ISSUE THREAD

**Issue by primengrocker** [primefaces/primeicons#333]
Hi please add pin and unpin icons. Thanks

**Comment by inad9300** [comment]
I'm interested in this as well. As a general question, what expectations should we have to respect to icon requests? They seem to be progressing incredibly slowly.

**Comment by ShawnTalbert** [comment]
It's been 2 years since the original request - any news?

**Comment by jepsar** [comment]
Why? There already is "map-marker".

**Comment by TheMukhtarAhmed** [comment]
yo how long you guys will take to add this icon?
