### ISSUE TITLE
Add "Instagram" icon

### ISSUE THREAD

**Issue by cristiandmocho** [primefaces/primeicons#334]
There's an icon for Facebook and Twitter, I'd like to suggest an icon for Instagram.

**Comment by KamilBanaszkiewicz** [comment]
I am agree, that would be great

**Comment by TakCastel** [comment]
Hello, I need an Instagram icon for my application, do you know when this icon will be available ? Thank you !

**Comment by onursenture** [comment]
Resolved here https://github.com/primefaces/primeicons/issues/455
