### ISSUE TITLE
Add "Vkontakte" icon

### ISSUE THREAD

**Issue by Japonaira** [primefaces/primeicons#367]
Could you please add an icon for [Vkontakte](vk.com)  social networking site? Attached you can find an example.  It's the most popular social in CIS countries. 
Many thanks in advance! 
![25684](https://user-images.githubusercontent.com/80126462/110165215-aac57100-7e03-11eb-9cf3-cebe536dd2cd.png)

**Comment by onursenture** [comment]
There is no common use-case of this icon for other users of PrimeIcons.
