### ISSUE TITLE
Add "refresh" icon

### ISSUE THREAD

**Issue by petrxh** [primefaces/primeicons#44]
Please add refresh or sync icon.
Thank you.

**Comment by onursenture** [comment]
pi-refresh is already exists.

**Comment by FacePalmDev** [comment]
Pi refresh looks like redo. I feel like refresh should look something like this to differentiate it from the other two. 

![image](https://user-images.githubusercontent.com/4026553/169775818-c63a748f-e399-4f02-906a-10f186a74eed.png)
****
