### ISSUE TITLE
Collapse and expand icon

### ISSUE THREAD

**Issue by Carmen1968** [primefaces/primeicons#541]

**Comment by jermylucas** [comment]
@Carmen1968 What are you wanting this to look like? Most people just use either the: closed and open folder icons, minus and plus icons, or up and down arrow icons. Is there something else you are wanting it to look like?

**Comment by onursenture** [comment]
Hi, Could you please open issues separately for each icon request? Thank you.

+

We'll need the answer to the question @jermylucas asked.
