### ISSUE TITLE
Add missing 'pi-server' file to PrimeIcons Constants

### ISSUE THREAD

**Issue by Raphzor** [primefaces/primeicons#556]
The icon `pi pi-server` is documented on the main site, but doesn't exist as a constant:

![image](https://user-images.githubusercontent.com/6784683/145825745-2880b157-d783-4fbf-a70b-d577a9aaccfe.png)

![image](https://user-images.githubusercontent.com/6784683/145825841-70134334-3f7f-4351-8c10-cb578484827e.png)

**Comment by onursenture** [comment]
It seems it's already fixed. Please check https://github.com/primefaces/primeng/blob/master/src/app/components/api/primeicons.ts

Thank you.
