### ISSUE TITLE
Add Delete icon also

### ISSUE THREAD

**Issue by Shubham98765** [primefaces/primeicons#560]
Delete icon or crash icon

**Comment by LouLeGrain** [comment]
What about this one ?

![Capture d’écran 2021-12-20 093428](https://user-images.githubusercontent.com/9808953/146737048-4f97e079-8cba-4e0e-a2b6-60f5751b2497.jpg)

**Comment by onursenture** [comment]
We already have **pi-trash**. Thanks.
