### ISSUE TITLE
Add "rosette" or "trophy" icon

### ISSUE THREAD

**Issue by jepsar** [primefaces/primeicons#629]
![rosette](https://user-images.githubusercontent.com/7500178/160370512-5d644d5e-13ed-4e86-a52e-21697331d6ff.jpeg)

![trophy](https://user-images.githubusercontent.com/7500178/160370517-e76ce092-8931-4ddd-940c-4aaae575152d.jpeg)

**Comment by onursenture** [comment]
Duplicate of #257
