### ISSUE TITLE
Country Flag

### ISSUE THREAD

**Issue by wvalverde67** [primefaces/primeicons#633]
Currently developing an app related to all our offices. We have offices in several countries and we would like to have the flag of every country in the corresponding menu option. In primeicons, I can't find flags of any country in the world.

Thanks in advance.

**Comment by flawesomesoft** [comment]
would appreciate this too. I need for selecting between different languages

**Comment by onursenture** [comment]
Since PrimeIcons is a font-icon library, it only offers mono-color icons (for now). We recommend you to use flag class like this one: https://github.com/primefaces/primeng/blob/55605c9c5d731455177cb5dd680249d044bd9063/src/app/showcase/components/table/tablestatedemo.html#L46
