### ISSUE TITLE
Add "bitcoin" icon

### ISSUE THREAD

**Issue by gesker** [primefaces/primeicons#644]
Could you add the BTC (Bitcoing) Cryptocurrency Icon?

https://www.google.com/search?q=bitcoin+symbol&tbm=isch&ved=2ahUKEwjlrMannIL3AhUTNH0KHc90BygQ2-cCegQIABAA&oq=bitcoin+symbol&gs_lcp=CgNpbWcQAzIICAAQgAQQsQMyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQ6BwgjEO8DECc6BAgAEEM6BggAEAcQHlDRCFjEFmDjGWgAcAB4AIABzQGIAfMKkgEFMC43LjGYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=EP1OYuXkEJPo9APP6Z3AAg&bih=974&biw=1920

**Comment by onursenture** [comment]
Duplicate of #321
