### ISSUE TITLE
How to create custom icon?

### ISSUE THREAD

**Issue by xreider** [primefaces/primeicons#693]
How to create custom icon and use them in PrimeFace?

**Comment by adrian-morfi** [comment]
Hi @onursenture, 

I'm very interested in this question too. I want to know how to integrate a custom SVG icon with the rest of the prime icons in Reactjs for example.

Thank you!

**Comment by thomasbalsloev** [comment]
I'm very interested in this too.

**Comment by jepsar** [comment]
See https://discord.com/channels/787967399105134612/787971222767927356/1098221722039222313 and https://www.youtube.com/watch?v=cQ91ieniOfQ&ab_channel=CagatayCivici
