### ISSUE TITLE
add Icon for add sub-group and remove sub-group ico

### ISSUE THREAD

**Issue by veereshrevadalaemerson** [primefaces/primeicons#694]
Could we have an icon added for adding sub-group items and as well remove the same
![image](https://user-images.githubusercontent.com/100938201/174534223-1203e046-88a2-4e1f-a474-5fee1d6648d1.png)

**Comment by onursenture** [comment]
Hi, Since there is no common use-case for this icon, we decided not to add. Thank you for suggestion.
