### ISSUE TITLE
Add "cake-candles" icon

### ISSUE THREAD

**Issue by jeanbaptis123** [primefaces/primeicons#737]
Please, add one or two related to "birthday"/ "cake" / "anniversary" in my current project I managed using heroicons and that was complex and not the proper way.

**Comment by jeanbaptis123** [comment]
Please, add one or two related to "birthday"/ "cake" / "anniversary" in my current project I managed using heroicons and that was complex and not the proper way.

**Comment by onursenture** [comment]
Duplicate of #316
