### ISSUE TITLE
Add wifi signal strength indicator icons

### ISSUE THREAD

**Issue by VanDulti** [primefaces/primeicons#745]
There is already a wifi icon 
![image](https://user-images.githubusercontent.com/74293813/185813776-64518d46-5a1d-4055-97a1-41936b75f0a8.png)

but no such thing to display the wifi signal strength similar to this for example:
[https://stock.adobe.com/de/search?k=signalst%C3%A4rke&asset_id=508028345](url)

**Comment by onursenture** [comment]
Hi, Sorry but there is no common use-case of this icon for other users of PrimeIcons. Thanks for suggestion.
