### ISSUE TITLE
Add icon "circle" as a draw on map

### ISSUE THREAD

**Issue by fcarbone-dgm** [primefaces/primeicons#763]
Add icon "circle" included in a set of icons to draw or indicate a circle on map

**Comment by onursenture** [comment]
We have already **pi-circle**. Thanks.

**Comment by fcarbone-dgm** [comment]
> We have already **pi-circle**. Thanks.

This icon will be used to indicate the activation of drawing/modifyng of a circle type area as an example below:

![Circle_vector_draw_icon](https://user-images.githubusercontent.com/67747939/189647503-e2ca667d-488e-4541-a769-d7467e95c15e.png)
