### ISSUE TITLE
Add icon "fly" or "airplane"

### ISSUE THREAD

**Issue by Vartanov** [primefaces/primeicons#765]

**Comment by onursenture** [comment]
We have "pi-send" icon. Thank you.

**Comment by Ruslancic** [comment]
I have asked for Airplane, not for send! Sometimes we need an Icon for airplane mode on mobile device, so pi-send it has nothing in common with with it!...

**Comment by onursenture** [comment]
> I have asked for Airplane, not for send! Sometimes we need an Icon for airplane mode on mobile device, so pi-send it has nothing in common with with it!...

OK. It's already in issue tracker. Duplicate of #219
