### ISSUE TITLE
Add "phone" icon

### ISSUE THREAD

**Issue by VRV64** [primefaces/primeicons#77]

**Comment by jepsar** [comment]
Can this please include a stand alone "receiver"?

**Comment by Hentaro1989** [comment]
I need it too.

**Comment by jepsar** [comment]
> I'm assuming an old school desk phone is requested. Can the new icons please also include a stand alone "receiver"?
> 
> https://www.thegreenhead.com/imgs/retro-bluetooth-handset-2.jpg

@onursenture I see only one icon has been added. Which one did you add? A desktop phone, or a receiver?

**Comment by onursenture** [comment]
This one: https://github.com/primefaces/primeicons/blob/master/raw-svg/phone.svg
