### ISSUE TITLE
Add pin icon

### ISSUE THREAD

**Issue by justcoder1** [primefaces/primeicons#802]

**Comment by onursenture** [comment]
We have **pi-map-marker**. Thank you.

**Comment by acmadden** [comment]
While I don't know the original intent of this issue, I would like to chime in. While the map icon works, it would be nice to have a _thumb-tack_ or _sewing-pin_ style of "pin".

Looks like there is already an issue, #333, for this exact icon, but I commented on this issue as it has the most recent activity regarding "pins".
