### ISSUE TITLE
Please add pin icon

### ISSUE THREAD

**Issue by TheMukhtarAhmed** [primefaces/primeicons#809]

**Comment by jepsar** [comment]
Duplicate of #333

**Comment by inad9300** [comment]
@jepsar what expectations should we have with respect to icon requests? They seem to be completely stalled. Should we have any hopes of ever having a bigger icon library in PrimeReact et al.? The current set is pretty limited.

**Comment by jepsar** [comment]
I don't know. I'm a PrimeFaces community committer, not a PrimeTek employee. Just helping a hand here by triaging issues.

**Comment by inad9300** [comment]
@onursenture how about you? Poor @jepsar is breaking his back here giving his time away for free, it'd be good to make it be worth something :wink:
