### ISSUE TITLE
Add "build", "comment" and "save" icons

### ISSUE THREAD

**Issue by AdnanSalah84** [primefaces/primeicons#81]
**Build Icon:**
https://material.io/tools/icons/?search=build&icon=build&style=baseline

**Comment Icon:**
https://material.io/tools/icons/?search=comment&icon=comment&style=baseline

**Save Icon:**
https://material.io/tools/icons/?search=save&icon=save&style=baseline

**Comment by onursenture** [comment]
Please create a separate ticket per icon request.
