### ISSUE TITLE
Add icons for accountant

### ISSUE THREAD

**Issue by 24012009** [primefaces/primeicons#821]
Could you add icons for accounting system. 
1. Chart of account.
2. Customer.
3. Vendor
4. Product and service
5. Estimate
6. Invoice
7. Sale Receipt
8. Receive payment
9. Credit memo or refund
10. Purchase
11. Bill
12. Pay Bill
13. Check Payment
14. Vendor credit
15. Reports
Thank you.

**Comment by samh0lmes** [comment]
I would also love an icon for vendor! 

Or store...something like this
<img width="40" alt="image" src="https://user-images.githubusercontent.com/16512986/199644741-16f6f5fa-0050-44cc-b800-77a59873f1f4.png">

<img width="115" alt="image" src="https://user-images.githubusercontent.com/16512986/199644655-16b2db0b-3a74-4187-b7d2-c125c371ed11.png"> (MdOutlineStore - material design icons)

**Comment by onursenture** [comment]
Hi, Could you please open issues separately for each icon request? Thank you.
