### ISSUE TITLE
Icon "pi-sync" is missing

### ISSUE THREAD

**Issue by SomaGC16** [primefaces/primeicons#861]
Hi, I tried to use the icon like normally do in my web but the icon is missing, it only happens with this icon, all others are fine.

Thanx!!

<img width="178" alt="image" src="https://user-images.githubusercontent.com/77362789/209354668-98cbce37-a9e4-48b2-b906-0c3844b42d20.png">

**Comment by onursenture** [comment]
We have "pi-sync" for this. Thank you.
