### ISSUE TITLE
Add "Document" icon

### ISSUE THREAD

**Issue by adrianodaddiego** [primefaces/primeicons#885]
![image](https://user-images.githubusercontent.com/6798884/217369818-eb6b6b9c-b4d8-4a8d-b92d-f22a358301eb.png)
add icon for document/sheet like this

**Comment by LouLeGrain** [comment]
Maybe [this one ](https://github.com/primefaces/primeicons/blob/master/raw-svg/file.svg) would fit ?

**Comment by adrianodaddiego** [comment]
> Maybe [this one ](https://github.com/primefaces/primeicons/blob/master/raw-svg/file.svg) would fit ?

Thanks
