### ISSUE TITLE
Add "expand" icon

### ISSUE THREAD

**Issue by masterworgen** [primefaces/primeicons#896]
Please add reminder icon like

![image](https://user-images.githubusercontent.com/19784438/221530165-5631a2d6-4e41-4d29-a725-7a8f24fe5963.png)

**Comment by nblum** [comment]
I think we would need multiple icons for fullscreen and make small again. Typically:
![image](https://user-images.githubusercontent.com/7358767/227462305-087c6b28-30a5-4c57-ab2c-a01ee0540559.png)
