### ISSUE TITLE
Add backward and forward icons with times (5, 10, ...)

### ISSUE THREAD

**Issue by Adrii77** [primefaces/primeicons#906]

**Comment by jepsar** [comment]
There already are `pi-forward` and `pi-backward` (and a fast and step variant).

**Comment by Adrii77** [comment]
Yes, you're right.

I was thinking to something like this :
![image](https://user-images.githubusercontent.com/40627664/226887386-0ae2564e-2bd7-4d74-841e-246f4af85611.png)

**Comment by jepsar** [comment]
Ah, thanks for making that clear!

**Comment by onursenture** [comment]
“We cannot add it since it is not a common use case for other PrimeIcons users. Thank you.”
