### ISSUE TITLE
please add 'New' Icon 

### ISSUE THREAD

**Issue by hubE79** [primefaces/primeicons#969]

**Comment by hubE79** [comment]
If possible 'New' as a word, in a fa fa icon or pi icon  :)

**Comment by hubE79** [comment]
Something like this: 

![new](https://github.com/primefaces/primeicons/assets/135716205/c5a86a1a-af42-4872-9166-7b89357950f4)

**Comment by onursenture** [comment]
> Possible duplicate of #908

+1
