### ISSUE TITLE
Please Can you add certificate icon

### ISSUE THREAD

**Issue by NellyAntoine** [primefaces/primeicons#970]
for example
https://www.flaticon.com/fr/icone-gratuite/certificat_3135807?related_id=3135763&origin=search

**Comment by NellyAntoine** [comment]
well, ok thks

**Comment by leonardocbalbino** [comment]
Tentei usar o pi pi-verified mas não exibe no projeto. Alguém sabe o motivo?

**Comment by onursenture** [comment]
> There already is `pi-verified`

+1
