### ISSUE TITLE
Move Icon

### ISSUE THREAD

**Issue by janakiram-madurai** [primefaces/primeicons#980]
We have an icon for copy, the same way can we add a icon for move action?

**Comment by jepsar** [comment]
@janakiram-madurai Can you please add an example?

**Comment by janakiram-madurai** [comment]
@jepsar please find this one.

https://www.veryicon.com/icons/miscellaneous/first/move-22.html

**Comment by onursenture** [comment]
Hi, Sorry but there is no common use-case of this icon for other users of PrimeIcons. Thanks for suggestion.
