### ISSUE TITLE
Add "microchip-ai" icon

### ISSUE THREAD

**Issue by felaris** [primefaces/primeicons#982]
I was thinking if there can be an icon that can be used to represent an AI(Primereact Icon)

**Comment by seyfer** [comment]
do you mean the OpenAI logo as an icon?

**Comment by felaris** [comment]
Not that but i mean any icon that can be used to represent "AI"

**Comment by felaris** [comment]
![ai_icon](https://github.com/primefaces/primeicons/assets/57809664/2c9deec9-57f4-4b5e-85ec-c24b4e2619aa)
![4](https://github.com/primefaces/primeicons/assets/57809664/caf3e6e0-d9b3-40dc-bc37-b4a01aaf2c80)

Something like this @jepsar

**Comment by felaris** [comment]
@jepsar this issue is still open
