### ISSUE TITLE
Add the filled version of the pi-shopping-cart icon

### ISSUE THREAD

**Issue by mlc-mlapis** [primefaces/primeicons#995]
Hi,

I want to ask if adding a filled version of the `pi-shopping-cart` icon is possible. The reason is that the filled version allows the better-placed text (in white) on the top layer of it because if you place the characters over the non-filled version, there is less space and contrast.

![image](https://github.com/primefaces/primeicons/assets/5693835/538b0058-f2c0-496b-bcc5-5963fc4e39e8)
![image](https://github.com/primefaces/primeicons/assets/5693835/ba149526-7c69-4ef7-9079-4dd38870cb4c)

**Comment by jepsar** [comment]
I think your use is a bit too specific. You could also just create a custom SVG for this use.

**Comment by mlc-mlapis** [comment]
@jepsar Yes, it's project-specific, but the idea was not to create something that duplicates PrimeIcons, and because there are already some filled icon versions, it has looked like it's not a bad idea to continue in the same direction.

**Comment by onursenture** [comment]
We only create 'fill' icons for actions that can be toggled, such as the open and closed versions of a 'heart' icon. We don't make fill icons just for cosmetic purposes.
