### ISSUE TITLE
add a gender icon

### ISSUE THREAD

**Issue by LuleJayjay** [primefaces/primeicons#998]
gender icons are missing.
at least for femal and male would be nice for category filtering for sports tourneys e.g.

**Comment by jepsar** [comment]
Duplicate of #206

**Comment by shantaly** [comment]
+1 on that

**Comment by jepsar** [comment]
> +1 on that

You might want to upvote #206 in that case

**Comment by onursenture** [comment]
> Duplicate of #206

+1
